spring.application.name=tontine-saas

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/tontine_saas
spring.datasource.username=fokanendapascal
spring.datasource.password=Pfn1306_l
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# I18N
# ===============================
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

# ===============================
# SECURITY
# ===============================
security.jwt.secret="secret-key-for-jwt-token-that-should-be-long"
security.jwt.access-exp-ms=3600000
security.jwt.refresh-exp-ms=1209600000

# ===============================
# SERVER
# ===============================
server.port=8080